version: '3'

services:

  library_service:
    build:
      context: .
      dockerfile: service.Dockerfile
    container_name: library_service
    environment:
      PORT: 5700
    links:
      - "db" # create an alias through which the service can connect to the database
    ports:
      - "5700:5700" # the service is available to users on first port
    restart: always

  db:
    build:
      context: .
      dockerfile: mysql.Dockerfile
    container_name: test_db
    env_file:
      - mysql.env
    expose:
      - "3306"
    volumes:                             # Now this is unnecessary, since the tables are recreated every time.
      - "./mysql/storage:/var/lib/mysql" # But it is important to remember when working with the database.


